### ISSUE TITLE
use.caRpools error

### ISSUE THREAD

**Issue by heather-watkins** [boutroslab/caRpools#10]
I have downloaded the virtual box, following the instructions.  When I ran use.caRpools, I received the following error message.  Do you have any suggestions of how I can fix this?

Creating a generic function for 'nchar' from package 'base' in package 'S4Vectors'
Quitting from lines 342-382 (CaRpools-extended-PDF.Rmd) 
 Show Traceback
 
 Rerun with Debug
 Error: 1: Space required after the Public Identifier
2: SystemLiteral " or ' expected
3: SYSTEM or PUBLIC, the URI is missing 

Thank you,

Heather Watkins

**Comment by jwinter6** [comment]
Hi Heather,
oh I had this a long time ago and cannot remember what this caused.
I will look into this in the next weeks as I am currently finishing my PhD thesis.

In the meantime you could also try CRISPRAnalyzeR as this is more intuitive, powerful and interactive than caRpools (it was meant as the successor).

Best
Jan

**Comment by heather-watkins** [comment]
Thank you!  I got some help from our IT help desk. It turns out the virtual machine was not connecting to the internet properly.

Best,

Heather

On Mar 16, 2018, at 2:51 AM, Jan Winter <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Heather,
oh I had this a long time ago and cannot remember what this caused.
I will look into this in the next weeks as I am currently finishing my PhD thesis.

In the meantime you could also try CRISPRAnalyzeR as this is more intuitive, powerful and interactive than caRpools (it was meant as the successor).

Best
Jan

**Comment by heather-watkins** [comment]
My IT help desk fixed the problem.  The virtual machine was not connecting to the internet.

Heather
