### ISSUE TITLE
Mistakes in Vignette

### ISSUE THREAD

**Issue by DarioS** [boutroslab/caRpools#5]
I noticed some important errors in the vignette which would affect all analysis. Firstly, the end of the promoter sequence is missing. The end of promoter shown on the [GeCKO Protocols](http://genome-engineering.org/gecko/?page_id=15) webpage in the Readout primers for Illumina sequencing of sgRNA cassette spreadsheet is CACC**G**. By using the pattern CACC, caRpools is extracting the last nucleotide of the U6 promoter as the first base of the guide sequence.

Also, we have noticed SNPs and indels at the beginning of the promoter sequence. By using only the short pattern CACC, caRpools treats promoter sequences with SNPs and indels in the same way as those which don't have them. But, isn't transcription from the promoter affected by these variants? Could there be a better search pattern that avoids matching these promoters? An example of such a read is

    CGATCGATACAGGTATTCTTGTGGAAAGGAGAAAACACCGGATCTCATGCTGTGACTCTCGTTTTAGAGCTAGAA
                    TCTTGTGGAAAGGACGAAACACCG
                                  MM

I put `MM` where the 2 SNPs are. Another example with two indels is:

    TAAGTAGAGTCTTGTGGAAAGGACGGAAACACCGCTTGCAGTACTGACATATCGGTTTTAGAGCTAGAAATAGCA
             TCTTGTGG-AAAGACG-AAACACCG

The backbone sequence is almost always perfect, so there's no issue at the opposite flank to think about.

Secondly, the illustration of the plasmid structure shows an incorrect guide length. It states that it is 20 nt, but if the red letters are counted, there are only 18. If you consider that the first red letter is really the last base of the U6 promoter, then this guide is 17 nt long.

![not20](https://cloud.githubusercontent.com/assets/631218/20853604/158ee0a2-b941-11e6-9950-6eecaa8583a7.png)

**Comment by jwinter6** [comment]
Hi Dario,
thanks a lot for your post above.

In regards to the figure you are right, I missed 2 basepairs there - sorry for that.

In regards to the CACCG issue, this also depends on the sgRNA FASTA file you provide. Sometime people add a G in front of any sgRNA target sequence, which becomes, once cloned with BbsI that provides CACC overhangs, a CACCG. If the G is present in the sgRNA FASTA file, you have to use CACC within the regular expression (as the additional G is part of your library file), if the G is present in the sgRNA, but not in the sgRNA FASTA file (so not present in the library file, but there in the sequencing), you have to use CACCG.

With the standard regular expression, which is shown both in the vignette and the figures, you are right that it does not work out of the box for the Gecko library.

Please note that the vignette and figures describe the principal use or caRpools with the provided sample files - and need to be adjusted if you want to use different screening libraries.

For this, you need to change the regular expression that extracts the FASTQ information from the sequencing file. With the standard setting, it only works for the CACC standard vectors.
You can adjust this within the MIACCS file:
![miaccs-new 2016-12-03 18-31-55](https://cloud.githubusercontent.com/assets/7203572/20861058/e56af370-b986-11e6-8e7a-c49b98fb4e44.png)

To your question with the CACC SNPs you observe:

- usually we do not see any SNP within the U6 promoter region in our sequencing data, but
- you can adjust the regular expression to catch everything including SNPs - It all depends only on the regular expression, which gives you a high power and flexibility.

Example 1:
`CGATCGATACAGGTATTCTTGTGGAAAGGAGAAAACACCGGATCTCATGCTGTGACTCTCGTTTTAGAGC`
If you want to exclude ANY mismatch/SNPs, no matter if they are just sequencing errors or not, you can do this with this regular expression pattern:

`.*TTCTTGTGGAAAGGAGAAAACACC(.{20,21})GT`
In case this is a real SNP and not just a sequencing/PCR mistake, it would make sense to exclude them.

Please let me know if you need additional help/information.

Best,
Jan

**Comment by DarioS** [comment]
> ... it does not work out of the box for the Gecko library.

Thanks for clarifying this. It's confusing to readers browsing the vignette because it states

> By default, this is ACC(.{20})GT{2,4}AGAGC and can be used for the GeckoV2 library ...

This pattern doesn't have the terminal G on the U6 promoter.

Do you know about any publications which evaluate how many reads have a perfect match to the U6 promoter sequence? Are there any publicly available high quality datasets that could be used to evaluate this? I noticed that the group who developed the method [didn't make the data available](http://science.sciencemag.org/content/343/6166/84.full) in a database such as [SRA](https://www.ncbi.nlm.nih.gov/sra).
